doc: Add the sd-jwt vc description in sdjwt.js.org
openwallet-foundation-labs/sd-jwt-js pull request #124
Opened 2024-02-29 05:22 UTC by lukasjhan

I added description of sd-jwt vc to our homepage.
I wrote a simple one based on what @cre8 wrote in the readme. :)

If there is anything you would like to write more about, please let me know.

2024-02-29 05:25 UTC, cre8 commented
Maybe we should also add the package to the readme in the root folder.

And later a part "who is using sd-jwt" and link there the Veramo and credo integration

2024-02-29 05:28 UTC, lukasjhan commented
> Maybe we should also add the package to the readme in the root folder.
> 
> And later a part "who is using sd-jwt" and link there the Veramo and credo integration

I'll add it right away

2024-02-29 07:26 UTC, cre8 requested changes

2024-02-29 07:26 UTC, cre8 commented on README.md
> +- **draft-ietf-oauth-selective-disclosure-jwt-07**
```suggestion
- **[draft-ietf-oauth-selective-disclosure-jwt-07](https://datatracker.ietf.org/doc/draft-ietf-oauth-selective-disclosure-jwt/)**
```

2024-02-29 07:26 UTC, cre8 commented on README.md
> +- **draft-ietf-oauth-sd-jwt-vc-02**
```suggestion
- **[draft-ietf-oauth-sd-jwt-vc-02](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-02.html)**
```

2024-02-29 09:30 UTC, lukasjhan commented
@cre8 I updated README with your suggestion :)

2024-03-01 09:23 UTC, cre8 approved these changes

2024-03-01 09:23 UTC, merged